name: Get Logs

on:
  workflow_dispatch:

jobs:
  get-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Log Directory
        run: mkdir -p workflow-logs

      - name: Get Logs
        uses: veracode-australia/policy-app-action@main
        with:
          action: retrieveLogs
          repository_full_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: veracode-logs
          path: workflow-logs
          if-no-files-found: error
