name: List Repositories in the Organization

on:
  workflow_dispatch:

jobs:
  dispatch-event:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repositories (Page 1)
        id: get_repos
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.repos.listForOrg({
              org: 'vsdeng-veracode-qan',
              per_page: 100,
              page: 1
            });
            console.log(data.map(repo => repo.full_name).join('\n'));
            console.log(`::set-output name=repos::${data.map(repo => repo.full_name).join('\n')}`);
