name: List Repositories in Organization

on:
  workflow_dispatch:

jobs:
  get-org-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'vsdeng-veracode-qan/verademo-java-maven-no-config'
          ref: 'main'
          token: ${{ secrets.GH_TOKEN }}
