name: List Repositories in Organization

on:
  workflow_dispatch:

jobs:
  get-org-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'vsdeng-veracode-qan/verademo-java-maven-no-config'
          ref: 'main'
          ssh-key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII/EU2AllI0cx7MMO93d8Qe6ar5PQmGVw5FnYg6OaYKp'
