name: List Repositories in Organization

on:
  workflow_dispatch:

jobs:
  get-org-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'verademo-java-maven-no-config'
          token: ${{ secrets.GH_TOKEN }}
