name: List Organisation Repositories

on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install gh CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
          
      - name: List Repositories (Replace with your org name)
        run: |
          gh repo list vsdeng-veracode-qan --limit 1000 --json name,description,visibility,html_url,clone_url > repos.json
       
      - name: Convert to CSV
        run: |
          echo "Repository Name,Description,Visibility,HTML URL,Clone URL" > repos.csv
          jq -r '.[] | [.name, .description, .visibility, .html_url, .clone_url] | @csv' repos.json >> repos.csv
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: repository-list
          path: repos.csv
