name: Scan Repository

run-name: Static Code Analysis - ${{ github.event.client_payload.repository_full_name }}

on:
  repository_dispatch:
    types:
      - veracode-policy-scan-package

jobs:
  veracode-policy-scan:
    name: Run Veracode Policy Scan
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repository_full_name }}
          token: ${{ secrets.ACCESS_TOKEN }}
          path: "source-code-repo"

      - uses: actions/checkout@v4
        with:
          path: "veracode-helper"

      - name: Package the appliccation
        env:
          VERACODE_API_KEY_ID: "${{ secrets.VERACODE_API_ID }}"
          VERACODE_API_KEY_SECRET: "${{ secrets.VERACODE_API_KEY }}"
        run: |
          cd veracode-helper/helper/cli
          cliFile=$(ls -1 . | head -n 1)
          cliFileName=$(echo "$cliFile" | cut -c 1-$((${#cliFile}-7)))
          tar -zxvf $cliFile
          cd $cliFileName
          chmod +x install.sh
          ./install.sh system
          cd /home/runner/work/veracode-scan/veracode-scan/source-code-repo
          veracode package --source . --output veracode-artifacts --trust --debug
          zip veracode-artifact.zip veracode-artifacts/* -x .zip .tar .tar.gz .gz

      - name: Veracode Upload and Scan Action Step
        uses: veracode/uploadandscan-action@main
        id: upload_and_scan
        with:
          appname: ${{ github.event.client_payload.repository_full_name }}
          createprofile: true
          policy: "Verademo Policy"
          version: "${{ github.run_id }}"
          filepath: /home/runner/work/veracode-scan/veracode-scan/source-code-repo/veracode-artifacts/
          deleteincompletescan: true
          vid: "${{ secrets.VERACODE_API_ID }}"
          vkey: "${{ secrets.VERACODE_API_KEY }}"
          failbuild: false
