name: VeracodePackage

on:
  workflow_dispatch:  
  schedule:
    # Runs at 00:00 (midnight) UTC every Monday
    - cron: '0 0 * * MON'

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check for .csproj files
      id: check_csproj
      run: |
        if ((Get-ChildItem -Recurse -Filter *.csproj).Count -eq 0) {
          echo "No .csproj files found."
          echo "continue=false" >> $env:GITHUB_ENV
        } else {
          echo "Found .csproj files."
          echo "continue=true" >> $env:GITHUB_ENV
        }

    - name: install CLI
      if: env.continue == 'true'
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install veracode-cli

    - name: Add MSBuild to PATH
      if: env.continue == 'true'
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      if: env.continue == 'true'
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Package and save output
      if: env.continue == 'true'
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        $outputFile = "${{ github.event.repository.name }}_veracode_log.txt"
        veracode package -das ${{env.SOLUTION_FILE_PATH}} 2>&1 | Tee-Object -FilePath $outputFile

    - name: Upload veracode output as artifact
      if: env.continue == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: veracode-package-log
        path: ${{ github.event.repository.name }}_veracode_log.txt
