name: Trigger Veracode Scan

on:
  workflow_dispatch:
    inputs:
      batch:
        required: true
        type: string

jobs:
  dispatch-event:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Check out the repository
      - name: Tigger Veracode Scan in Another Workflow
        env:
          CSV_FILE: repositories.csv # Name of your CSV file
        run: |
          count=0
          while IFS=, read -r repo batch _; do  
            if [[ -n "$repo" && "${batch## }" == "1" ]]; then  
              echo "Triggering scan for: $repo"
              echo "Triggering scan for: $batch"
              curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/vsdeng-veracode-qan/veracode-scan/dispatches \
                -d '{"event_type": "veracode-policy-scan-net", "client_payload": {"repository_full_name": "'"$repo"'"}}'
              count=$((count + 1))
              if [[ $count -eq 10 ]]; then
                echo "Pausing for 20 seconds..." 
                sleep 20  # Wait for 20 seconds
                count=0   # Reset counter
              fi
            fi
          done < $CSV_FILE
