name: Trigger Veracode Scan

on:
  workflow_dispatch:
    inputs:
      batch:
        required: true
        type: string

jobs:
  dispatch-event:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Check out the repository
      - name: Tigger Veracode Scan in Another Workflow
        uses: veracode-australia/policy-app-action@main
        with:
          action: triggerPoicyScan
          batch_number: ${{ github.event.inputs.batch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
