name: Build Artifact for Veracode Code Analysis

on:
  workflow_call:
    inputs:
      repository_full_name:
        required: true
        type: string
      event_name:
        required: true
        type: string
      image:
        required: true
        type: string
      access_token:
        required: true
        type: string

jobs:
  build:
    if: ${{ inputs.event_name == 'veracode-policy-scan-package' }}
    uses: ./.github/workflows/veracode-default-build.yml
    with:
      repository_full_name: ${{ inputs.repository_full_name }}
      image: ${{ inputs.image }}
      access_token: ${{ inputs.access_token }}
