name: Veracode Build

on:
  workflow_call:
    inputs:
      repository_full_name:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.image }}
    # container:
    #   image: ${{ inputs.build_packager_image }}
    env:
      VERACODE_API_KEY_ID: "${{ secrets.VERACODE_API_ID }}"
      VERACODE_API_KEY_SECRET: "${{ secrets.VERACODE_API_KEY }}"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository_full_name }}
          token: ${{ secrets.ACCESS_TOKEN }}
          path: "source-code-repo"

      - uses: actions/checkout@v4
        with:
          path: "veracode-helper"

      - name: Package the application
        id: application_package
        shell: bash
        env:
          VERACODE_API_KEY_ID: "${{ secrets.VERACODE_API_ID }}"
          VERACODE_API_KEY_SECRET: "${{ secrets.VERACODE_API_KEY }}"
        run: |
          working_path=`pwd`
          echo "working_dir=$working_path" >> "$GITHUB_OUTPUT"
          cd veracode-helper/helper/cli
          cliFile=$(ls -1 . | head -n 1)
          cliFileName=$(echo "$cliFile" | cut -c 1-$((${#cliFile}-7)))
          tar -zxvf $cliFile
          cd $cliFileName
          cliPath=`pwd`
          export PATH="$cliPath:$PATH"
          echo $PATH
          cd $working_path/source-code-repo
          veracode package --source . --output $working_path/veracode-artifacts --trust

      - name: Package error
        if: failure() && steps.application_package.outcome == 'failure'
        run: |
          echo "::error::Veracode static scan faced a problem. Please contact your Veracode administrator for more information."

      - uses: actions/upload-artifact@v4
        with:
          name: veracode-artifact
          path: "${{ steps.application_package.outputs.working_dir }}/veracode-artifacts/*"
          if-no-files-found: error
